In [13]:
import numpy as np

In [25]:
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],
    
    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],
    
    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

n=[1,2,3,4,5,6,7,8,9]

In [36]:
for i in range(0,9,3):
    for j in range(0,9,3):
        print(s[i:i+3,j:j+3].sum())

45
45
45
45
45
45
45
45
45


In [15]:
adr=np.sum(s,axis=1)
for i in ad:
    if i!=45:
        print("Not sudoku")
        break
print("row sudoku")

row sudoku


In [16]:
adc=np.sum(s,axis=0)
for i in adc:
    if i!=45:
        print("not sudoku")
        break
print("col sudoku")

col sudoku


In [17]:
for i in range(0,9,3):
    for j in range(0,9,3):
        num=s[i:i+3,j:j+3]
        print(num)

[[5 3 4]
 [6 7 2]
 [1 9 8]]
[[6 7 8]
 [1 9 5]
 [3 4 2]]
[[9 1 2]
 [3 4 8]
 [5 6 7]]
[[8 5 9]
 [4 2 6]
 [7 1 3]]
[[7 6 1]
 [8 5 3]
 [9 2 4]]
[[4 2 3]
 [7 9 1]
 [8 5 6]]
[[9 6 1]
 [2 8 7]
 [3 4 5]]
[[5 3 7]
 [4 1 9]
 [2 8 6]]
[[2 8 4]
 [6 3 5]
 [1 7 9]]


In [22]:
for i in num:
    print( num.sum())

45
45
45


In [50]:
import numpy as np

# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])

In [39]:
#Get the shape of the matrix.
data.shape

(5, 3)

In [40]:
#Find the average age of students.
age=data[0: , 0]
avg=np.mean(age)
avg
# avgc=np.mean(data,axis=1) #col
# avgr=np.mean(data,axis=0) #row
# avgc,

np.float64(18.4)

In [41]:
#Extract Math marks of all students.
mathMark=data[0: ,1]
mathMark

array([85, 92, 76, 65, 90])

In [42]:
#Find the highest Science mark. 
science=data[0: ,2]
result=max(science)
result


np.int64(95)

In [43]:
#Get details of the student who scored more than 90 in Math. 
for i in range(len(mathMark)):
    if mathMark[i]>90:
        print(data[i,0:])
        break

[19 92 88]


In [44]:
#Increase Math marks of all students by 5.
new_math_mark=mathMark+5
new_math_mark

array([90, 97, 81, 70, 95])

In [45]:
#Find how many students are younger than 19.

count=0
for i in age:
    if i>19:
        count+=1
count

1

In [46]:
#Calculate the average marks in each subject (column-wise mean).
avgMath=np.mean(mathMark)
avgMath




np.float64(81.6)

In [47]:
avgScience=np.mean(science)
avgScience

np.float64(83.2)

In [48]:
#Calculate the average marks in each subject (column-wise mean).
avgMarks=np.mean(data[: , 1: ],axis=0)
avgMarks

array([81.6, 83.2])

In [49]:
#Get data of students who scored at least 80 in both subjects.
getData=data[(data[: , 1 ]>=80) & (data[: ,2]>=80)]
getData
# for i in range(0,5):
#     if mathMark[i]>=80 and science[i]>=80:
#         print(data[i])

array([[19, 92, 88],
       [20, 90, 85]])

In [51]:
#Replace all Science marks < 75 with 0.
data[:,2][data[:,2]<75]=0
data
# for i in range(0,5):
#     if science[i]<75:
#         science[i]=0

# science

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65,  0],
       [20, 90, 85]])